apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::798234419462:role/eksctl-kubesight-aws-cni-nodegrou-NodeInstanceRole-G9H21GS3MHM3
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::798234419462:role/eksctl-kubesight-aws-cni-nodegrou-NodeInstanceRole-2N8YR767XFQ3
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::798234419462:role/eksctl-kubesight-aws-cni-nodegrou-NodeInstanceRole-NVXS6EWQIL4I
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::798234419462:role/KarpenterNodeRole-kubesight-aws-cni
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
